### ISSUE TITLE
Create a map zoom navigation control

### ISSUE THREAD

**Issue by eltomali** [Pihlqvist/wallmap#54]
Now we either scroll or double click on the map to zoom in the map. It is not clear for the user who doesn't know how to zoom. Most maps have a zoom control. It would be good to create one for usability.

**Comment by Pihlqvist** [comment]
Implemented in [demo](https://github.com/Pihlqvist/wallmap/commit/2a3016a038b49e4ad47fcf50c91ba04d18336b72)

**Comment by Pihlqvist** [comment]
This was fixed in #81
